CREATE TABLE configuracion (
	rutaTorre VARCHAR(30) NOT NULL DEFAULT "img/torres",
	rutaEnemigo VARCHAR(30) NOT NULL DEFAULT "img/enemigos",
	rutaEscenario VARCHAR(30) NOT NULL DEFAULT "img/escenarios",
	medidaVentanaJuego VARCHAR(30) NOT NULL DEFAULT "960*540",
	filasRanking TINYINT UNSIGNED NOT NULL DEFAULT 50
);


CREATE TABLE administrador(
	id TINYINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nombre VARCHAR(60) NOT NULL,
	perfil VARCHAR(2) NOT NULL CHECK(perfil='LP'),
	clave VARCHAR(255) NOT NULL
); 

CREATE TABLE enemigos(
	id TINYINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nombre VARCHAR(90) NOT NULL UNIQUE,
	velocidadMov TINYINT UNSIGNED NOT NULL,
	puntos INT NOT NULL,
	nombreImagen VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE torres(
	id TINYINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nombre VARCHAR(90) NOT NULL UNIQUE,
	radioActuacion smallint UNSIGNED NOT NULL,
	velocidadRecorrido TINYINT UNSIGNED NOT NULL,
	nombreImagen VARCHAR(50) UNIQUE NOT NULL
); 

CREATE TABLE dificultad(
	id TINYINT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
	nombre CHAR(6) NOT NULL
);

CREATE TABLE escenario(
	id TINYINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nombre VARCHAR(90) NOT NULL UNIQUE,
	nombreImagen VARCHAR(50) UNIQUE NOT NULL,
	idDificultad TINYINT UNSIGNED NOT NULL,
	CONSTRAINT FK_idDificultad FOREIGN KEY (idDificultad) REFERENCES dificultad (id)escenario 
);

CREATE TABLE ranking(
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	alias VARCHAR(20) NOT NULL,
	puntos INT UNSIGNED NOT NULL
); 