/*DROP TABLE IF EXISTS administrador;
DROP TABLE IF EXISTS configuracion;
DROP TABLE IF EXISTS escenario;
DROP TABLE IF EXISTS dificultad;
DROP TABLE IF EXISTS torres;
DROP TABLE IF EXISTS usuarios;
DROP TABLE IF EXISTS enemigos;
DROP TABLE IF EXISTS ranking;*/

CREATE TABLE lp_configuracion (
	rutaTorre VARCHAR(30) NOT NULL DEFAULT "img/torres",
	rutaEnemigo VARCHAR(30) NOT NULL DEFAULT "img/enemigos",
	rutaEscenario VARCHAR(30) NOT NULL DEFAULT "img/escenarios",
	medidaVentanaJuego VARCHAR(30) NOT NULL DEFAULT "960*544",
	filasRanking TINYINT UNSIGNED NOT NULL DEFAULT 50
);

CREATE TABLE lp_administrador(
	id TINYINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nombre VARCHAR(60) NOT NULL,
	perfil VARCHAR(2) NOT NULL CHECK(perfil='LP'),
	clave VARCHAR(255) NOT NULL
); 

CREATE TABLE lp_enemigos(
	id TINYINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nombre VARCHAR(90) NOT NULL UNIQUE,
	velocidadMov TINYINT UNSIGNED NOT NULL,
	puntos INT NOT NULL,
	nombreImagen VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE lp_torres(
	id TINYINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nombre VARCHAR(90) NOT NULL UNIQUE,
	radioActuacion smallint UNSIGNED NOT NULL,
	velocidadRecorrido TINYINT UNSIGNED NOT NULL,
	nombreImagen VARCHAR(50) UNIQUE NOT NULL
); 

CREATE TABLE lp_dificultad(
	id TINYINT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
	nombre CHAR(7) NOT NULL
);

CREATE TABLE lp_escenario(
	id TINYINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nombre VARCHAR(90) NOT NULL UNIQUE,
	nombreImagen VARCHAR(50) UNIQUE NOT NULL,
	idDificultad TINYINT UNSIGNED NOT NULL,
	CONSTRAINT FK_idDificultad FOREIGN KEY (idDificultad) REFERENCES dificultad (id)
);

CREATE TABLE lp_ranking(
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	alias VARCHAR(20) NOT NULL,
	puntos INT UNSIGNED NOT NULL
);

INSERT INTO lp_configuracion (rutaTorre, rutaEnemigo, rutaEscenario, medidaVentanaJuego, filasRanking)
				VALUES(DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
 				
INSERT INTO lp_dificultad(nombre)
				VALUES	('Fácil'),
						('Media'),
						('Difícil');